Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
import pickle

Importing the datasets

In [2]:
dataset = pd.read_csv('Datasets/changesInGet/modifyNewColumn.csv')
X = dataset.iloc[:, 1:-1]
y = dataset.iloc[:, -1]

Presenting dataset

In [3]:
X.head()

itching  Male  Female  Age(1-20)  Age(21-40)  Age(40-above)   skin_rash  \
0        1     0       1          0           1              0           1   
1        0     0       1          1           0              0           1   
2        1     1       0          1           0              0           0   
3        1     0       1          0           1              0           1   
4        1     1       0          1           0              0           1   

    nodal_skin_eruptions   dischromic _patches   continuous_sneezing  ...  \
0                      1                     1                     0  ...   
1                      1                     1                     0  ...   
2                      1                     1                     0  ...   
3                      0                     1                     0  ...   
4                      1                     0                     0  ...   

    bladder_discomfort   foul_smell_of urine   continuous_feel_of_urine  \
0                    0                     0                          0   
1                    0                     0                          0   
2                    0                     0                          0   
3                    0                     0                          0   
4                    0                     0                          0   

    skin_peeling   silver_like_dusting   small_dents_in_nails  \
0              0                     0                      0   
1              0                     0                      0   
2              0                     0                      0   
3              0                     0                      0   
4              0                     0                      0   

    inflammatory_nails   blister   red_sore_around_nose   yellow_crust_ooze  
0                    0         0                      0                   0  
1                    0         0                      0                   0  
2                    0         0                      0                   0  
3                    0         0                      0                   0  
4                    0         0                      0                   0  

[5 rows x 136 columns]

In [4]:
y.head()

0    Fungal infection
1    Fungal infection
2    Fungal infection
3    Fungal infection
4    Fungal infection
Name: Disease, dtype: object

Splitting the dataset to train and test set

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Presenting the splitted dataset 

In [6]:
X_train.head()

itching  Male  Female  Age(1-20)  Age(21-40)  Age(40-above)   skin_rash  \
613         1     0       1          1           0              0           0   
4155        1     0       1          1           0              0           0   
3803        0     1       0          0           1              0           0   
3321        1     0       1          1           0              0           1   
3790        0     0       1          1           0              0           0   

       nodal_skin_eruptions   dischromic _patches   continuous_sneezing  ...  \
613                       0                     0                     0  ...   
4155                      0                     0                     0  ...   
3803                      0                     0                     0  ...   
3321                      1                     1                     0  ...   
3790                      0                     0                     0  ...   

       bladder_discomfort   foul_smell_of urine   continuous_feel_of_urine  \
613                     0                     0                          0   
4155                    0                     0                          0   
3803                    0                     0                          0   
3321                    0                     0                          0   
3790                    0                     0                          0   

       skin_peeling   silver_like_dusting   small_dents_in_nails  \
613               0                     0                      0   
4155              0                     0                      0   
3803              0                     0                      0   
3321              0                     0                      0   
3790              0                     0                      0   

       inflammatory_nails   blister   red_sore_around_nose   yellow_crust_ooze  
613                     0         0                      0                   0  
4155                    0         0                      0                   0  
3803                    0         0                      0                   0  
3321                    0         0                      0                   0  
3790                    0         0                      0                   0  

[5 rows x 136 columns]

In [7]:
y_train.head()

613          Hepatitis B
4155            Jaundice
3803      Hypothyroidism
3321    Fungal infection
3790             Typhoid
Name: Disease, dtype: object

In [8]:
X_test.head()

itching  Male  Female  Age(1-20)  Age(21-40)  Age(40-above)   skin_rash  \
1525        0     1       0          0           0              0           0   
1013        0     1       0          0           0              0           0   
1892        0     1       0          1           0              0           0   
1972        0     0       1          0           1              0           0   
873         0     1       0          1           0              0           0   

       nodal_skin_eruptions   dischromic _patches   continuous_sneezing  ...  \
1525                      0                     0                     0  ...   
1013                      0                     0                     0  ...   
1892                      0                     0                     0  ...   
1972                      0                     0                     0  ...   
873                       0                     0                     0  ...   

       bladder_discomfort   foul_smell_of urine   continuous_feel_of_urine  \
1525                    0                     0                          0   
1013                    0                     0                          0   
1892                    0                     0                          0   
1972                    0                     0                          0   
873                     0                     0                          0   

       skin_peeling   silver_like_dusting   small_dents_in_nails  \
1525              0                     0                      0   
1013              0                     0                      0   
1892              0                     0                      0   
1972              0                     0                      0   
873               0                     0                      0   

       inflammatory_nails   blister   red_sore_around_nose   yellow_crust_ooze  
1525                    0         0                      0                   0  
1013                    0         0                      0                   0  
1892                    0         0                      0                   0  
1972                    0         0                      0                   0  
873                     0         0                      0                   0  

[5 rows x 136 columns]

In [9]:
y_test.head()

1525           Heart attack
1013            hepatitis A
1892           Tuberculosis
1972           Hypoglycemia
873     Peptic ulcer diseae
Name: Disease, dtype: object

In [10]:
X_train.count()

itching                  3936
Male                     3936
Female                   3936
Age(1-20)                3936
Age(21-40)               3936
                         ... 
 small_dents_in_nails    3936
 inflammatory_nails      3936
 blister                 3936
 red_sore_around_nose    3936
 yellow_crust_ooze       3936
Length: 136, dtype: int64

In [11]:
X_test.count()

itching                  984
Male                     984
Female                   984
Age(1-20)                984
Age(21-40)               984
                        ... 
 small_dents_in_nails    984
 inflammatory_nails      984
 blister                 984
 red_sore_around_nose    984
 yellow_crust_ooze       984
Length: 136, dtype: int64

Training the train set on decision tree classification model and predicting the accuracy score

In [12]:
classifier_dst = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_dst.fit(X_train, y_train)
y_pred = classifier_dst.predict(X_test)
accuracy_score(y_test, y_pred)

1.0

Finding confusion matrix of decision tree classifier model

In [13]:
confusion_matrix(y_test, y_pred)

array([[18,  0,  0, ...,  0,  0,  0],
       [ 0, 22,  0, ...,  0,  0,  0],
       [ 0,  0, 31, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 20,  0,  0],
       [ 0,  0,  0, ...,  0, 28,  0],
       [ 0,  0,  0, ...,  0,  0, 24]])

Predicting the value using decision tree classification

In [14]:
print(classifier_dst.predict([[1,0,1,0,1,0,0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]]))

['Heart attack']


/Users/dhirajbarela/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


Training the model on random forest classification model and finding the accuracy score

In [15]:
classifier_RFC = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_RFC.fit(X_train, y_train)
y_pred = classifier_RFC.predict(X_test)
accuracy_score(y_test, y_pred)

1.0

Finding confusion matrix of random forest classifier model

In [16]:
confusion_matrix(y_test, y_pred)

array([[18,  0,  0, ...,  0,  0,  0],
       [ 0, 22,  0, ...,  0,  0,  0],
       [ 0,  0, 31, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 20,  0,  0],
       [ 0,  0,  0, ...,  0, 28,  0],
       [ 0,  0,  0, ...,  0,  0, 24]])

Predicting the value using random forest classification model

Training the model on logistic regression classification and finding accuracy ratio

In [17]:
classifier_LR = LogisticRegression(random_state = 0)
classifier_LR.fit(X_train, y_train)
y_pred = classifier_LR.predict(X_test)
accuracy_score(y_test, y_pred)

1.0

Finding confusion matrix of logistic regression classifier model

In [18]:
confusion_matrix(y_test, y_pred)

array([[18,  0,  0, ...,  0,  0,  0],
       [ 0, 22,  0, ...,  0,  0,  0],
       [ 0,  0, 31, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 20,  0,  0],
       [ 0,  0,  0, ...,  0, 28,  0],
       [ 0,  0,  0, ...,  0,  0, 24]])

Training the model on kernel support vector machine classification and finding accuracy ratio

In [19]:
classifier_svm = SVC(kernel = 'rbf', random_state = 0)
classifier_svm.fit(X_train, y_train)
y_pred = classifier_svm.predict(X_test)
accuracy_score(y_test, y_pred)

1.0

Finding confusion matrix of support vector machine classifier model

In [20]:
confusion_matrix(y_test, y_pred)

array([[18,  0,  0, ...,  0,  0,  0],
       [ 0, 22,  0, ...,  0,  0,  0],
       [ 0,  0, 31, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 20,  0,  0],
       [ 0,  0,  0, ...,  0, 28,  0],
       [ 0,  0,  0, ...,  0,  0, 24]])

Convert the best predicting model that is the logistic regression model to pickle format

In [21]:
# Assuming you have already trained a model and assigned it to the variable "my_model"
# Save the trained model to a file

with open('my_model.pkl', 'wb') as f:
    pickle.dump(classifier_LR, f)