Importing libraries

In [131]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
import pickle

Importing the datasets

In [132]:
dataset = pd.read_csv('Datasets/changesInGet/modifyNewColumn.csv')
X = dataset.iloc[:, 1:-1]
y = dataset.iloc[:, -1]

Presenting dataset

In [133]:
X.head()

itching  Male  Female  Age(1-20)  Age(21-40)  Age(40-above)   skin_rash  \
0        1     0       1          0           1              0           1   
1        0     0       1          1           0              0           1   
2        1     1       0          1           0              0           0   
3        1     0       1          0           1              0           1   
4        1     1       0          1           0              0           1   

    nodal_skin_eruptions   dischromic _patches   continuous_sneezing  ...  \
0                      1                     1                     0  ...   
1                      1                     1                     0  ...   
2                      1                     1                     0  ...   
3                      0                     1                     0  ...   
4                      1                     0                     0  ...   

    bladder_discomfort   foul_smell_of urine   continuous_feel_of_urine  \
0                    0                     0                          0   
1                    0                     0                          0   
2                    0                     0                          0   
3                    0                     0                          0   
4                    0                     0                          0   

    skin_peeling   silver_like_dusting   small_dents_in_nails  \
0              0                     0                      0   
1              0                     0                      0   
2              0                     0                      0   
3              0                     0                      0   
4              0                     0                      0   

    inflammatory_nails   blister   red_sore_around_nose   yellow_crust_ooze  
0                    0         0                      0                   0  
1                    0         0                      0                   0  
2                    0         0                      0                   0  
3                    0         0                      0                   0  
4                    0         0                      0                   0  

[5 rows x 136 columns]

In [134]:
y.head()

0    Fungal infection
1    Fungal infection
2    Fungal infection
3    Fungal infection
4    Fungal infection
Name: Disease, dtype: object

In [135]:
dataset.head()

Unnamed: 0  itching  Male  Female  Age(1-20)  Age(21-40)  Age(40-above)  \
0           0        1     0       1          0           1              0   
1           1        0     0       1          1           0              0   
2           2        1     1       0          1           0              0   
3           3        1     0       1          0           1              0   
4           4        1     1       0          1           0              0   

    skin_rash   nodal_skin_eruptions   dischromic _patches  ...  \
0           1                      1                     1  ...   
1           1                      1                     1  ...   
2           0                      1                     1  ...   
3           1                      0                     1  ...   
4           1                      1                     0  ...   

    foul_smell_of urine   continuous_feel_of_urine   skin_peeling  \
0                     0                          0              0   
1                     0                          0              0   
2                     0                          0              0   
3                     0                          0              0   
4                     0                          0              0   

    silver_like_dusting   small_dents_in_nails   inflammatory_nails   blister  \
0                     0                      0                    0         0   
1                     0                      0                    0         0   
2                     0                      0                    0         0   
3                     0                      0                    0         0   
4                     0                      0                    0         0   

    red_sore_around_nose   yellow_crust_ooze           Disease  
0                      0                   0  Fungal infection  
1                      0                   0  Fungal infection  
2                      0                   0  Fungal infection  
3                      0                   0  Fungal infection  
4                      0                   0  Fungal infection  

[5 rows x 138 columns]

Describe dataset properties

In [136]:
dataset.describe()

Unnamed: 0      itching         Male       Female    Age(1-20)  \
count  4920.000000  4920.000000  4920.000000  4920.000000  4920.000000   
mean   2459.500000     0.137805     0.494309     0.505691     0.500203   
std    1420.425992     0.344730     0.500018     0.500018     0.500051   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%    1229.750000     0.000000     0.000000     0.000000     0.000000   
50%    2459.500000     0.000000     0.000000     1.000000     1.000000   
75%    3689.250000     0.000000     1.000000     1.000000     1.000000   
max    4919.000000     1.000000     1.000000     1.000000     1.000000   

        Age(21-40)  Age(40-above)    skin_rash   nodal_skin_eruptions  \
count  4920.000000         4920.0  4920.000000            4920.000000   
mean      0.249187            0.0     0.159756               0.021951   
std       0.432586            0.0     0.366417               0.146539   
min       0.000000            0.0     0.000000               0.000000   
25%       0.000000            0.0     0.000000               0.000000   
50%       0.000000            0.0     0.000000               0.000000   
75%       0.000000            0.0     0.000000               0.000000   
max       1.000000            0.0     1.000000               1.000000   

        dischromic _patches  ...   bladder_discomfort   foul_smell_of urine  \
count           4920.000000  ...          4920.000000           4920.000000   
mean               0.021951  ...             0.023171              0.020732   
std                0.146539  ...             0.150461              0.142499   
min                0.000000  ...             0.000000              0.000000   
25%                0.000000  ...             0.000000              0.000000   
50%                0.000000  ...             0.000000              0.000000   
75%                0.000000  ...             0.000000              0.000000   
max                1.000000  ...             1.000000              1.000000   

        continuous_feel_of_urine   skin_peeling   silver_like_dusting  \
count                4920.000000    4920.000000           4920.000000   
mean                    0.023171       0.023171              0.023171   
std                     0.150461       0.150461              0.150461   
min                     0.000000       0.000000              0.000000   
25%                     0.000000       0.000000              0.000000   
50%                     0.000000       0.000000              0.000000   
75%                     0.000000       0.000000              0.000000   
max                     1.000000       1.000000              1.000000   

        small_dents_in_nails   inflammatory_nails      blister  \
count            4920.000000          4920.000000  4920.000000   
mean                0.023171             0.023171     0.023171   
std                 0.150461             0.150461     0.150461   
min                 0.000000             0.000000     0.000000   
25%                 0.000000             0.000000     0.000000   
50%                 0.000000             0.000000     0.000000   
75%                 0.000000             0.000000     0.000000   
max                 1.000000             1.000000     1.000000   

        red_sore_around_nose   yellow_crust_ooze  
count            4920.000000         4920.000000  
mean                0.023171            0.023171  
std                 0.150461            0.150461  
min                 0.000000            0.000000  
25%                 0.000000            0.000000  
50%                 0.000000            0.000000  
75%                 0.000000            0.000000  
max                 1.000000            1.000000  

[8 rows x 137 columns]

Splitting the dataset to train and test set

In [137]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.98, random_state = 0)

In [138]:
X_train.head()

itching  Male  Female  Age(1-20)  Age(21-40)  Age(40-above)   skin_rash  \
1987        0     0       1          1           0              0           0   
931         0     1       0          0           0              0           0   
4226        1     0       1          0           1              0           0   
3455        0     0       1          1           0              0           0   
4651        0     0       1          1           0              0           0   

       nodal_skin_eruptions   dischromic _patches   continuous_sneezing  ...  \
1987                      0                     0                     0  ...   
931                       0                     0                     0  ...   
4226                      0                     0                     0  ...   
3455                      0                     0                     0  ...   
4651                      0                     0                     0  ...   

       bladder_discomfort   foul_smell_of urine   continuous_feel_of_urine  \
1987                    0                     0                          0   
931                     0                     0                          0   
4226                    0                     0                          0   
3455                    0                     0                          0   
4651                    0                     0                          0   

       skin_peeling   silver_like_dusting   small_dents_in_nails  \
1987              0                     0                      0   
931               0                     0                      0   
4226              0                     0                      0   
3455              0                     0                      0   
4651              0                     0                      0   

       inflammatory_nails   blister   red_sore_around_nose   yellow_crust_ooze  
1987                    0         0                      0                   0  
931                     0         0                      0                   0  
4226                    0         0                      0                   0  
3455                    0         0                      0                   0  
4651                    0         0                      0                   0  

[5 rows x 136 columns]

In [139]:
y_train.head()

1987        Osteoarthristis
931                Migraine
4226    Chronic cholestasis
3455               Migraine
4651                Typhoid
Name: Disease, dtype: object

In [140]:
X_test.head()

itching  Male  Female  Age(1-20)  Age(21-40)  Age(40-above)   skin_rash  \
1525        0     1       0          0           0              0           0   
1013        0     1       0          0           0              0           0   
1892        0     1       0          1           0              0           0   
1972        0     0       1          0           1              0           0   
873         0     1       0          1           0              0           0   

       nodal_skin_eruptions   dischromic _patches   continuous_sneezing  ...  \
1525                      0                     0                     0  ...   
1013                      0                     0                     0  ...   
1892                      0                     0                     0  ...   
1972                      0                     0                     0  ...   
873                       0                     0                     0  ...   

       bladder_discomfort   foul_smell_of urine   continuous_feel_of_urine  \
1525                    0                     0                          0   
1013                    0                     0                          0   
1892                    0                     0                          0   
1972                    0                     0                          0   
873                     0                     0                          0   

       skin_peeling   silver_like_dusting   small_dents_in_nails  \
1525              0                     0                      0   
1013              0                     0                      0   
1892              0                     0                      0   
1972              0                     0                      0   
873               0                     0                      0   

       inflammatory_nails   blister   red_sore_around_nose   yellow_crust_ooze  
1525                    0         0                      0                   0  
1013                    0         0                      0                   0  
1892                    0         0                      0                   0  
1972                    0         0                      0                   0  
873                     0         0                      0                   0  

[5 rows x 136 columns]

In [141]:
y_test.head()

1525           Heart attack
1013            hepatitis A
1892           Tuberculosis
1972           Hypoglycemia
873     Peptic ulcer diseae
Name: Disease, dtype: object

In [142]:
X_train.count()

itching                  98
Male                     98
Female                   98
Age(1-20)                98
Age(21-40)               98
                         ..
 small_dents_in_nails    98
 inflammatory_nails      98
 blister                 98
 red_sore_around_nose    98
 yellow_crust_ooze       98
Length: 136, dtype: int64

In [143]:
X_test.count()

itching                  4822
Male                     4822
Female                   4822
Age(1-20)                4822
Age(21-40)               4822
                         ... 
 small_dents_in_nails    4822
 inflammatory_nails      4822
 blister                 4822
 red_sore_around_nose    4822
 yellow_crust_ooze       4822
Length: 136, dtype: int64

Training the train set on decision tree classification model and predicting the accuracy score

In [144]:
classifier_dst = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_dst.fit(X_train, y_train)
y_pred = classifier_dst.predict(X_test)
accuracy_score(y_test, y_pred)

0.7996681874740772

In [145]:
confusion_matrix(y_test, y_pred)

array([[104,   0,   0, ...,   0,   0,   0],
       [  0, 106,   0, ...,   0,   0,   0],
       [  0,   0, 101, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 102,   0,   0],
       [  0,   0,   0, ...,   0,  56,   0],
       [  0,   0,   0, ...,   0,   0, 106]])

Predicting the value using decision tree classification

In [147]:
print(classifier_dst.predict([[1,0,1,0,1,0,0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]]))

['Heart attack']


/Users/dhirajbarela/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


Training the model on random forest classification model and finding the accuracy score

In [148]:
classifier_RFC = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_RFC.fit(X_train, y_train)
y_pred = classifier_RFC.predict(X_test)
accuracy_score(y_test, y_pred)

0.871630029033596

In [149]:
confusion_matrix(y_test, y_pred)

array([[116,   0,   0, ...,   0,   0,   0],
       [  0, 114,   0, ...,   0,   0,   0],
       [  0,   0,  85, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 114,   0,   0],
       [  0,   0,   0, ...,   0,  40,   0],
       [  0,   0,   0, ...,   0,   0, 118]])

Predicting the value using random forest classification model

Training the model on logistic regression classification and finding accuracy ratio

In [150]:
classifier_LR = LogisticRegression(random_state = 0)
classifier_LR.fit(X_train, y_train)
y_pred = classifier_LR.predict(X_test)
accuracy_score(y_test, y_pred)

0.9361260887598507

In [151]:
confusion_matrix(y_test, y_pred)

array([[116,   0,   0, ...,   0,   0,   0],
       [  0, 118,   0, ...,   0,   0,   0],
       [  0,   0, 104, ...,   1,   0,   0],
       ...,
       [  0,   0,   0, ..., 114,   0,   0],
       [  0,   0,   0, ...,   0, 119,   0],
       [  0,   0,   0, ...,   0,   0, 118]])

Training the model on kernel support vector machine classification and finding accuracy ratio

In [152]:
classifier_svm = SVC(kernel = 'rbf', random_state = 0)
classifier_svm.fit(X_train, y_train)
y_pred = classifier_svm.predict(X_test)
accuracy_score(y_test, y_pred)

0.7376607216922438

In [153]:
confusion_matrix(y_test, y_pred)

array([[116,   0,   0, ...,   0,   0,   0],
       [  0, 118,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   6,   0,   0],
       ...,
       [  0,   0,   0, ..., 114,   0,   0],
       [  0,   0,   0, ...,  96,  23,   0],
       [  0,   0,   0, ...,   0,   0, 118]])

Convert the best predicting model that is the logistic regression model to pickle format

In [154]:
# Assuming you have already trained a model and assigned it to the variable "my_model"
# Save the trained model to a file
with open('my_model.pkl', 'wb') as f:
    pickle.dump(classifier_LR, f)
