Importing libraries

In [238]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression


Importing the datasets

In [239]:
dataset = pd.read_csv('Datasets/get.csv')
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

Presenting dataset

In [240]:
X.head()

itching   skin_rash   nodal_skin_eruptions   dischromic _patches  \
0        1           1                      1                     1   
1        0           1                      1                     1   
2        1           0                      1                     1   
3        1           1                      0                     1   
4        1           1                      1                     0   

    continuous_sneezing   shivering   chills   watering_from_eyes  \
0                     0           0        0                    0   
1                     0           0        0                    0   
2                     0           0        0                    0   
3                     0           0        0                    0   
4                     0           0        0                    0   

    stomach_pain   acidity  ...   bladder_discomfort   foul_smell_of urine  \
0              0         0  ...                    0                     0   
1              0         0  ...                    0                     0   
2              0         0  ...                    0                     0   
3              0         0  ...                    0                     0   
4              0         0  ...                    0                     0   

    continuous_feel_of_urine   skin_peeling   silver_like_dusting  \
0                          0              0                     0   
1                          0              0                     0   
2                          0              0                     0   
3                          0              0                     0   
4                          0              0                     0   

    small_dents_in_nails   inflammatory_nails   blister  \
0                      0                    0         0   
1                      0                    0         0   
2                      0                    0         0   
3                      0                    0         0   
4                      0                    0         0   

    red_sore_around_nose   yellow_crust_ooze  
0                      0                   0  
1                      0                   0  
2                      0                   0  
3                      0                   0  
4                      0                   0  

[5 rows x 131 columns]

In [241]:
y.head()

0    Fungal infection
1    Fungal infection
2    Fungal infection
3    Fungal infection
4    Fungal infection
Name: Disease, dtype: object

In [242]:
dataset.head()

itching   skin_rash   nodal_skin_eruptions   dischromic _patches  \
0        1           1                      1                     1   
1        0           1                      1                     1   
2        1           0                      1                     1   
3        1           1                      0                     1   
4        1           1                      1                     0   

    continuous_sneezing   shivering   chills   watering_from_eyes  \
0                     0           0        0                    0   
1                     0           0        0                    0   
2                     0           0        0                    0   
3                     0           0        0                    0   
4                     0           0        0                    0   

    stomach_pain   acidity  ...   foul_smell_of urine  \
0              0         0  ...                     0   
1              0         0  ...                     0   
2              0         0  ...                     0   
3              0         0  ...                     0   
4              0         0  ...                     0   

    continuous_feel_of_urine   skin_peeling   silver_like_dusting  \
0                          0              0                     0   
1                          0              0                     0   
2                          0              0                     0   
3                          0              0                     0   
4                          0              0                     0   

    small_dents_in_nails   inflammatory_nails   blister  \
0                      0                    0         0   
1                      0                    0         0   
2                      0                    0         0   
3                      0                    0         0   
4                      0                    0         0   

    red_sore_around_nose   yellow_crust_ooze           Disease  
0                      0                   0  Fungal infection  
1                      0                   0  Fungal infection  
2                      0                   0  Fungal infection  
3                      0                   0  Fungal infection  
4                      0                   0  Fungal infection  

[5 rows x 132 columns]

Describe dataset properties

In [243]:
dataset.describe()

itching    skin_rash   nodal_skin_eruptions   dischromic _patches  \
count  4920.000000  4920.000000            4920.000000           4920.000000   
mean      0.137805     0.159756               0.021951              0.021951   
std       0.344730     0.366417               0.146539              0.146539   
min       0.000000     0.000000               0.000000              0.000000   
25%       0.000000     0.000000               0.000000              0.000000   
50%       0.000000     0.000000               0.000000              0.000000   
75%       0.000000     0.000000               0.000000              0.000000   
max       1.000000     1.000000               1.000000              1.000000   

        continuous_sneezing    shivering       chills   watering_from_eyes  \
count           4920.000000  4920.000000  4920.000000          4920.000000   
mean               0.045122     0.021951     0.162195             0.021951   
std                0.207593     0.146539     0.368667             0.146539   
min                0.000000     0.000000     0.000000             0.000000   
25%                0.000000     0.000000     0.000000             0.000000   
50%                0.000000     0.000000     0.000000             0.000000   
75%                0.000000     0.000000     0.000000             0.000000   
max                1.000000     1.000000     1.000000             1.000000   

        stomach_pain      acidity  ...   bladder_discomfort  \
count    4920.000000  4920.000000  ...          4920.000000   
mean        0.045122     0.045122  ...             0.023171   
std         0.207593     0.207593  ...             0.150461   
min         0.000000     0.000000  ...             0.000000   
25%         0.000000     0.000000  ...             0.000000   
50%         0.000000     0.000000  ...             0.000000   
75%         0.000000     0.000000  ...             0.000000   
max         1.000000     1.000000  ...             1.000000   

        foul_smell_of urine   continuous_feel_of_urine   skin_peeling  \
count           4920.000000                4920.000000    4920.000000   
mean               0.020732                   0.023171       0.023171   
std                0.142499                   0.150461       0.150461   
min                0.000000                   0.000000       0.000000   
25%                0.000000                   0.000000       0.000000   
50%                0.000000                   0.000000       0.000000   
75%                0.000000                   0.000000       0.000000   
max                1.000000                   1.000000       1.000000   

        silver_like_dusting   small_dents_in_nails   inflammatory_nails  \
count           4920.000000            4920.000000          4920.000000   
mean               0.023171               0.023171             0.023171   
std                0.150461               0.150461             0.150461   
min                0.000000               0.000000             0.000000   
25%                0.000000               0.000000             0.000000   
50%                0.000000               0.000000             0.000000   
75%                0.000000               0.000000             0.000000   
max                1.000000               1.000000             1.000000   

           blister   red_sore_around_nose   yellow_crust_ooze  
count  4920.000000            4920.000000         4920.000000  
mean      0.023171               0.023171            0.023171  
std       0.150461               0.150461            0.150461  
min       0.000000               0.000000            0.000000  
25%       0.000000               0.000000            0.000000  
50%       0.000000               0.000000            0.000000  
75%       0.000000               0.000000            0.000000  
max       1.000000               1.000000            1.000000  

[8 rows x 131 columns]

Splitting the dataset to train and test set

In [244]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.98, random_state = 0)

In [245]:
X_train.head()

itching   skin_rash   nodal_skin_eruptions   dischromic _patches  \
1987        0           0                      0                     0   
931         0           0                      0                     0   
4226        1           0                      0                     0   
3455        0           0                      0                     0   
4651        0           0                      0                     0   

       continuous_sneezing   shivering   chills   watering_from_eyes  \
1987                     0           0        0                    0   
931                      0           0        0                    0   
4226                     0           0        0                    0   
3455                     0           0        0                    0   
4651                     0           0        1                    0   

       stomach_pain   acidity  ...   bladder_discomfort   foul_smell_of urine  \
1987              0         0  ...                    0                     0   
931               0         0  ...                    0                     0   
4226              0         0  ...                    0                     0   
3455              0         1  ...                    0                     0   
4651              0         0  ...                    0                     0   

       continuous_feel_of_urine   skin_peeling   silver_like_dusting  \
1987                          0              0                     0   
931                           0              0                     0   
4226                          0              0                     0   
3455                          0              0                     0   
4651                          0              0                     0   

       small_dents_in_nails   inflammatory_nails   blister  \
1987                      0                    0         0   
931                       0                    0         0   
4226                      0                    0         0   
3455                      0                    0         0   
4651                      0                    0         0   

       red_sore_around_nose   yellow_crust_ooze  
1987                      0                   0  
931                       0                   0  
4226                      0                   0  
3455                      0                   0  
4651                      0                   0  

[5 rows x 131 columns]

In [246]:
y_train.head()

1987        Osteoarthristis
931                Migraine
4226    Chronic cholestasis
3455               Migraine
4651                Typhoid
Name: Disease, dtype: object

In [247]:
X_test.head()

itching   skin_rash   nodal_skin_eruptions   dischromic _patches  \
1525        0           0                      0                     0   
1013        0           0                      0                     0   
1892        0           0                      0                     0   
1972        0           0                      0                     0   
873         0           0                      0                     0   

       continuous_sneezing   shivering   chills   watering_from_eyes  \
1525                     0           0        0                    0   
1013                     0           0        0                    0   
1892                     0           0        0                    0   
1972                     0           0        0                    0   
873                      0           0        0                    0   

       stomach_pain   acidity  ...   bladder_discomfort   foul_smell_of urine  \
1525              0         0  ...                    0                     0   
1013              0         0  ...                    0                     0   
1892              0         0  ...                    0                     0   
1972              0         0  ...                    0                     0   
873               0         0  ...                    0                     0   

       continuous_feel_of_urine   skin_peeling   silver_like_dusting  \
1525                          0              0                     0   
1013                          0              0                     0   
1892                          0              0                     0   
1972                          0              0                     0   
873                           0              0                     0   

       small_dents_in_nails   inflammatory_nails   blister  \
1525                      0                    0         0   
1013                      0                    0         0   
1892                      0                    0         0   
1972                      0                    0         0   
873                       0                    0         0   

       red_sore_around_nose   yellow_crust_ooze  
1525                      0                   0  
1013                      0                   0  
1892                      0                   0  
1972                      0                   0  
873                       0                   0  

[5 rows x 131 columns]

In [248]:
y_test.head()

1525           Heart attack
1013            hepatitis A
1892           Tuberculosis
1972           Hypoglycemia
873     Peptic ulcer diseae
Name: Disease, dtype: object

In [249]:
X_train.count()

itching                  98
 skin_rash               98
 nodal_skin_eruptions    98
 dischromic _patches     98
 continuous_sneezing     98
                         ..
 small_dents_in_nails    98
 inflammatory_nails      98
 blister                 98
 red_sore_around_nose    98
 yellow_crust_ooze       98
Length: 131, dtype: int64

In [250]:
X_test.count()

itching                  4822
 skin_rash               4822
 nodal_skin_eruptions    4822
 dischromic _patches     4822
 continuous_sneezing     4822
                         ... 
 small_dents_in_nails    4822
 inflammatory_nails      4822
 blister                 4822
 red_sore_around_nose    4822
 yellow_crust_ooze       4822
Length: 131, dtype: int64

Training the train set on decision tree classification model and predicting the accuracy score

In [251]:
classifier_dst = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_dst.fit(X_train, y_train)
y_pred = classifier_dst.predict(X_test)
accuracy_score(y_test, y_pred)


0.8369970966403982

In [252]:
confusion_matrix(y_test, y_pred)

array([[ 98,   0,   0, ...,   0,   0,   0],
       [  0, 106,   0, ...,   0,   0,   0],
       [  0,   0, 101, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 102,   0,   0],
       [  0,   0,   0, ...,   0, 107,   0],
       [  0,   0,   0, ...,   0,   0, 100]])

In [253]:
itching=1

Predicting the value using decision tree classification

In [254]:
print(classifier_dst.predict([[itching,0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]]))

['Heart attack']


/Users/dhirajbarela/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


Training the model on random forest classification model and finding the accuracy score

In [255]:
classifier_RFC = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier_RFC.fit(X_train, y_train)
y_pred = classifier_RFC.predict(X_test)
accuracy_score(y_test, y_pred)

0.9464952301949399

In [256]:
confusion_matrix(y_test, y_pred)

array([[116,   0,   0, ...,   0,   0,   0],
       [  0, 118,   0, ...,   0,   0,   0],
       [  0,   0, 119, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 114,   0,   0],
       [  0,   0,   0, ...,   0, 119,   0],
       [  0,   0,   0, ...,   0,   0, 118]])

Predicting the value using random forest classification model

In [257]:
print(classifier_RFC.predict([[1,0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]]))

['Heart attack']


/Users/dhirajbarela/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


Training the model on logistic regression classification and finding accuracy ratio

In [258]:
classifier_LR = LogisticRegression(random_state = 0)
classifier_LR.fit(X_train, y_train)
y_pred = classifier_LR.predict(X_test)
accuracy_score(y_test, y_pred)

0.950228121111572

In [259]:
confusion_matrix(y_test, y_pred)

array([[116,   0,   0, ...,   0,   0,   0],
       [  0, 118,   0, ...,   0,   0,   0],
       [  0,   0, 119, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ..., 114,   0,   0],
       [  0,   0,   0, ...,   0, 119,   0],
       [  0,   0,   0, ...,   0,   0, 118]])

Training the model on kernel support vector machine classification and finding accuracy ratio

In [260]:
classifier_svm = SVC(kernel = 'rbf', random_state = 0)
classifier_svm.fit(X_train, y_train)
y_pred = classifier_svm.predict(X_test)
accuracy_score(y_test, y_pred)

0.8672749896308586

In [261]:
confusion_matrix(y_test, y_pred)

array([[116,   0,   0, ...,   0,   0,   0],
       [  0, 118,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   6,   0,   0],
       ...,
       [  0,   0,   0, ..., 114,   0,   0],
       [  0,   0,   0, ...,   0, 119,   0],
       [  0,   0,   0, ...,   0,   0, 118]])